[package]
name = "lox"
version = "0.1.0"
authors = ["kydas <kadasilva22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scanlex = "0.1.4"
